M7R0
I&mylib=6"%&falseGE\[l*%%l1pGGw,6/%$alpG%%betaG%#p1G%#q1G%#t1G%#p2G%#q2G%#t2G%#
r1G%#s1G%#r2G%#s2G>'%%fullG%(booleanGF%6,%%alpnG%&betanG%$p1nG%$q1nG%$t1nG%$p2n
G%$q2nG%$t2nG%$p10G%"GG6"F$C1>8$-I'factorG6$%*protectedG%(_syslibG6#,&*&9$"""9,
FRFR*&9%FR9.FRFR>8%-FJ6#,&*&FQFR9-FRFR*&FUFR9/FRFR>8&-FJ6#*&,.*(FS""#FinFR9&FRF
R*(FSFaoFgnFR9)FR!""**FVFR9'FRFSFRFinFRFR**FSFR9*FRFgnFRFVFRFeo*(FVFaoFinFR9(FR
FR*(FVFaoFgnFR9+FRFeoFR,&*&FSFRFinFRFR*&FgnFRFVFRFeoFeo>8'-FJ6#*&,2**FSFRFgnFRF
inFRFboFRFao*(FgnFaoFSFRFdoFR!"#*(FinFaoFgoFRFSFRFR**FgnFRFinFRFVFRFgoFRFR**Fgn
FRFinFRFSFRFioFRFeo*(FgnFaoFioFRFVFRFeo*(FinFaoFVFRF[pFRFao**FVFRFinFRFgnFRF]pF
RFipFRF^pFeo>8(-FJ6#*&,.*(FgnFaoFinFRFboFRFR*&Fgn""$FdoFRFeo*(FgnFRFinFaoFgoFRF
R*(FgnFaoFinFRFioFRFeo*&FinFhqF[pFRFR*(FinFaoFgnFRF]pFRFeoFRF^pFeo>8)-FJ6#,$*&,
.*(FSFaoFVFRFboFRFR*&FSFhqFdoFRFeo*(FSFRFVFaoFgoFRFR*(FSFaoFVFRFioFRFeo*&FVFhqF
[pFRFR*(FVFaoFSFRF]pFRFeoFRF^pFeoFeo>8*-FJ6#,$*&,2**FSFRFgnFRFVFRFboFRFaoFcoFip
FfoFR*(FVFaoFgoFRFgnFRFR*(FSFaoFioFRFinFRFeoFhoFeoFjoFao**FVFRFinFRFSFRF]pFRFip
FRF^pFeoFeo>8+-FJ6#,$*&,.*(FgnFaoFVFRFboFRFRFhpFeoF[qFRF\qFeoF^qFR*(FinFaoFSFRF
]pFRFeoFRF^pFeoFeo>8,-%(convertG6$-I'MatrixG6$FLFM6#7#7$FQFU%%listG>8--Fdt6#7$7
%-FJ6#Fbo-FJ6#Fgo-FJ6#F[p7%-FJ6#Fdo-FJ6#Fio-FJ6#F]p@$90C'-&F"6#%(pprintfG6%Q?In
itial~coefficients:~~%a~=~%aF$)&%"pG6#""!$FRFjvF_t-Fav6$Q'G~=~%aF$F[u-Fav6'Q>su
bstitution:~~%a,~%a;~%a,~%aF$FSFgnFVFin-Fav6$Q)det:~~%aF$-I)simplifyG6$FLFM6#-F
J6#-Ffw6#-%&deltaG6&FSFgnFVFin-Fav6#QAcoefficients~after~substitution:F$>F_t-Fa
t6$-Fdt6#7#7$FHFXFit>F[u-Fdt6#7$7%-FJ6#F[o-FJ6#Fbp-FJ6#Faq7%-FJ6#F^r-FJ6#F[s-FJ
6#Ffs-Fav6%Q(%a~=~%aF$)FgvF[wF_tF\wF$F$F$6#"#7677&Q!F$Feo"#9"#!)7&FdzFeoFeo"#G7
&FdzFeo"#J"#h7&FdzFeoFeo"#'*7&FdzFeoFeo"$G"7&FdzFeoFeo"#))7&FdzFeoFeo"#*)7&FdzF
eoFeo"$H"7&FdzFeoFeo"#(*7&FdzFeoFeo"#R7&FdzFeoFeo"#$)7&FdzFeoFeo"#e7&FdzFeoFaz"
#x7&FdzFeoFR"#F7&FdzFeo"#I"##*7&FdzFeoFR"#u7&FdzFeoFR"#]7&FdzFeoFeo"#TFb[lFi\l7
&FdzFeo"#W"#q%"PGf*6(%"aG%"bG%"cG%"dG%"xG%"yGF$6$%)operatorG%&arrowGF$,**&FQFRF
[pFhqFR*(FUFRF[pFaoFdoFRFR*(FboFRF[pFRFdoFaoFR*&FgoFRFdoFhqFRF$F$F$Fcvw,6#'%"SG
%'stringG6)%"XG%"LG%"rG%"nG%"iG%"jG%"kG6"F$C(>FX7#-_I,StringToolsG6$FLFM%)RegSp
litG6$Q#%aF$FQ>FH7#&9"6#;FaoFeo>F[o%%NULLG>F^rFR?(FaqFRFR-%%nopsG6#FX%%trueGC&>
Fbp-_Fb_l%:CountCharacterOccurrencesG6$&FXFdyQ"%F$>F[o6$F[o-_I,TypesettingG6$FL
FM%#miG6#-I(sprintfG6$FLFM6$F[al-%$seqG6$&FHFiy/F[s;F^r,(F^rFRFbpFRFeoFR>F^r,&F
^rFRFbpFR@$1F^r-Fb`l6#FHC$>F[o6$F[o-%#opG6#-%$mapG6$_Faal%(TypesetG7#&FHFgy>F^r
,&F^rFRFRFR-%&printG6#-_Faal%%mrowGF`yF$F$F$6#FR6/7&FdzFeo"#<"#A7&FdzFeoFeo"#@7
&FdzFeo"#CF\]l7&FdzFeo"#Z"#c7&FdzFeo"#f"#l7&FdzFeoFeoFfz7&FdzFeoFR"#S7&FdzFeoFR
"#Y7&FdzFeoFh\lF]\l7&FdzFeoFR"#s7&FdzFeo"#B"#`7&FdzFeo"#dFidl7&FdzFeoFeoFaz%$pm
1Gw,6+%#a1G%#b1G%#c1G%#d1G%#a2G%#b2G%#c2G%#d2G>F7F%6+%$P1nG%$P2nG%&rez2nG%%chis
G%%znamG%$obwG%#omG%#gpG%#mnG6"F$C,>FH-FJ6#-Ffw6#-&F"6#F^]l6(FQFUFboFgo%#x1G%#x
2G>FX-FJ6#-Ffw6#-Ffgl6(F[pFdoFioF]pFiglFjgl>Fbp-%&numerG6#*&FHFRFXFeo>Faq-%&den
omGFehl>F^r-Ffw6#*&FHFRFbpFeo@%/-%&coeffG6$F^rFiglFRC$>F[s-Fdt6#7#7$F`il-Fail6$
F^rFjgl>Ffs-Fdt6#7$7%-FJ6#-Ffw6#-Fail6$Fbp*$FiglFao-FJ6#-Ffw6#*&-Fail6$FbpFiglF
RFjglFeo-FJ6#-Ffw6#-Fail6$Fbp*$FjglFao7%-FJ6#-Ffw6#-Fail6$FaqFfjl-FJ6#-Ffw6#*&-
Fail6$FaqFiglFRFjglFeo-FJ6#-Ffw6#-Fail6$FaqFd[mC&>F_tF`il>F[s-Fdt6#7#7$*&F`ilFR
F_tFeo*&FiilFRF_tFeo>Ffs-Fdt6#7$7%-FJ6#*&FbjlFRF_tFR-FJ6#*&FijlFRF_tFR-FJ6#-Ffw
6#*&Fb[mFRF_tFR7%-FJ6#*&Fh[mFRF_tFR-FJ6#*&F^\mFRF_tFR-FJ6#-Ffw6#*&Fg\mFRF_tFR@$
2&F[s6$FRFRFjvC$>F[s,$F[sFeo>Ffs,$FfsFeo>F[o-FJ6#-Ffw6#-I(combineG6$FLFM6#,&*$z
'6&&FfsFa_m&Ffs6$FRFhq&Ffs6$FaoFR&Ffs6$FaoFhq\[[[[[[[[\[[mFR[[[\[[\[[[[[mFeoFao
FR*&z'6&Fd`m&Ffs6$FRFaoFg`m&Ffs6$FaoFao\[[[[[[[[\[[mFR[[[\[[\[[[[[mFeoFRz'6&F^a
mFe`mF`amFi`m\[[[[[[[[\[[mFR[[[\[[\[[[[[mFeoFRFeo>F[s-Fat6$F[sFit@$/FSFd`lC(-Fa
v6#Q6Initial~coefficients:F$-Ffcl6&FQFUFboFgo-Ffcl6&F[pFdoFioF]p-Fav6#Q/Factori
zation:F$-Fav6%F^z)FgvF[wF[s-Fav6$F^wFfs-Fav6$Q4Resultant~of~G:~~%aF$F[oF$F$F$6
#"")6;7&FdzFeo"#8"#_7&FdzFeoFeoFh\lFbcm7&FdzFeoFeo"#?7&FdzFeoFcelF\]l7&FdzFeoFe
dl"#r7&FdzFeoFeo"#X7&FdzFeoFcelF]]l7&FdzFeoFR"#!*7&FdzFeo""%F_dl7&FdzFeo"#D"#y7
&FdzFeoFRF][l7&FdzFeoFRFj\l7&FdzFeo"#>Fhz7&FdzFeoFc\lF\el7&FdzFeoFeo"$\"Fccm7&F
dzFeoFeo"#")7&FdzFeoF^dl"#b7&FdzFeoFRFadlFbdl7&FdzFeoFedlFadm7&FdzFeoFR"#U7&Fdz
FeoF^el"#t7&FdzFeoFeoF`em%'l1systGw,6,F*F+F,F-F.F/F0F1>'%$lblGF9F%>'%$resGF9F%6
6%$a1nG%$b1nG%$c1nG%$d1nG%$a2nG%$b2nG%$c2nG%$d2nG%'rezultG%#i1G%#i2G%#i3G%#i4G%
#i5G%#i6G%#i7G%#i8G%#ixGFCFD6"F$C1>FH*&FQFRFboFR>FX,&*&FQFRFgoFRFR*&FboFRFUFRFR
>F[o,&*&FQFRF[pFRFR*&FUFRFgoFRFR>Fbp*&F[pFRFUFR>Faq*&FQFRFdoFR>F^r,&*&FQFRFioFR
FR*&FUFRFdoFRFR>F[s,&*&FQFRF]pFRFR*&FUFRFioFRFR>Ffs*&FUFRF]pFR>86F`t>87F\u-Fav6
%Fev)FgvF[wF[im-Fav6$F^wF]im@$FgnC$>F_t-FJ6#,&*$,&*&FboFRF]pFRFR*&FdoFRF[pFRFeo
FaoFR*&,&*&FboFRFioFRFR*&FdoFRFgoFRFeoFR,&*&FgoFRF]pFRFR*&FioFRF[pFRFeoFRFeo-Fa
v6$F[cmF_t-Fav6#Q.Matrix~(2x4):F$@%FSC*-FfclFebl-FfclFc`l-FfclF`y-FfclFby-FfclF
dy-FfclFgy-FfclFiy-FfclF[zC$-Ffcl6&FHFXF[oFbp-Ffcl6&FaqF^rF[sFfsF$F$F$6#F]cm6>7
&FdzFeo"#;"#nFgel7&FdzFeoFez"#N7&FdzFeo"#PF]\l7&FdzFeo"#gFf\lFgelF]\nF_\nFa\nFh
[lFj[l7&FdzFeoFeo"#k7&FdzFeoF\\n"#$*7&FdzFeoFeoFdel7&FdzFeo"#6Fgcm7&FdzFeoFRFic
m7&FdzFeoFeo"#H7&FdzFeoFeoFfel7&FdzFeoFazFadl7&FdzFeoFcdl"#L7&FdzFeo"#OFicm7&Fd
zFeo"#[FfelF^]nF_]nFa]nFc]n7&FdzFeoF^dmF`dm7&FdzFeoFhz"#\F^xf*6&Figl%#y1GFjgl%#
y2GF$6$Fh]lFi]lF$,&FfgmFRFggmFeoF$F$F$%(zamprocGw-61F[flF\flF]flF^flF_flF`flFaf
lFbflF2F3F4F5>F7F%>FhemF%>F[fmF%6F%%a1nnG%%b1nnG%%c1nnG%%d1nnG%%a2nnG%%b2nnG%%c
2nnG%%d2nnGF^fmF_fmF`fmFafmFbfmFcfmFdfmFefm%&DeltaGFgfmFhfmFifmFjfmF[gmF\gmF]gm
F^gmF_gm%#m1G%#m2G%#m3G%#m4G%#m5G%#m6G%#m7G%#m8G%#mxG%"MG6"F$CI>84F^p>F_t*&,&*&
FinFR-Ffgl6(FQFUFboFgoFSFVFRFR*&FgnFR-Ffgl6(F[pFdoFioF]pFSFVFRFeoFRF[`nFeo>F[u*
&,:**FQFRFSFaoFgnFRFinFRFhq*,FUFRFSFRFgnFRFVFRFinFRFao*(FUFRFSFaoFinFaoFR**FboF
RFSFRFVFRFinFaoFao**FboFRFgnFRFVFaoFinFRFR*(FgoFRFVFaoFinFaoFhq*(F[pFRFSFaoFgnF
ao!"$**FdoFRFSFRFgnFaoFVFRFip**FdoFRFSFaoFgnFRFinFRFeo*,FioFRFSFRFgnFRFVFRFinFR
Fip*(FioFRFgnFaoFVFaoFeo**F]pFRFgnFRFVFaoFinFRF_anFRF[`nFeo>8.*&,:**FQFRFSFRFgn
FaoFinFRFhq**FUFRFSFRFgnFRFinFaoFao**FUFRFgnFaoFVFRFinFRFR**FboFRFgnFRFVFRFinFa
oFao*(FboFRFSFRFinFhqFR*(FgoFRFVFRFinFhqFhq*(F[pFRFSFRFgnFhqF_an**FdoFRFSFRFgnF
aoFinFRFip*(FdoFRFgnFhqFVFRFeo**FioFRFgnFaoFVFRFinFRFip**FioFRFSFRFgnFRFinFaoFe
o**F]pFRFgnFRFVFRFinFaoF_anFRF[`nFeo>8/*&,&*&FinFR-Ffgl6(FQFUFboFgoFgnFinFRFR*&
FgnFR-Ffgl6(F[pFdoFioF]pFgnFinFRFeoFRF[`nFeo>80*&,&*&FVFRF``nFRFeo*&FSFRFc`nFRF
RFRF[`nFeo>81*&,:*(F[pFRFSFhqFgnFRFhq**FdoFRFSFaoFgnFRFVFRFao*(FdoFRFSFhqFinFRF
R**FioFRFSFaoFVFRFinFRFao**FioFRFSFRFgnFRFVFaoFR**F]pFRFSFRFVFaoFinFRFhq**FQFRF
SFaoFgnFRFVFRF_an**FUFRFSFRFgnFRFVFaoFip**FUFRFSFaoFVFRFinFRFeo**FboFRFSFRFVFao
FinFRFip*(FboFRFgnFRFVFhqFeo*(FgoFRFVFhqFinFRF_anFRF[`nFeo>82*&,:F^anFhqFaanFao
F`anFRFbanFao*(FioFRFSFaoFinFaoFR**F]pFRFSFRFVFRFinFaoFhq**FQFRFSFRFgnFaoFVFRF_
anFi`nFip*(FUFRFgnFaoFVFaoFeoF\anFipF[anFeoF]anF_anFRF[`nFeo>83*&,&*&FVFRFjbnFR
Feo*&FSFRF]cnFRFRFRF[`nFeo>FH-Ffw6#-FJ6#-Ffw6#-%'normalG6#-Ffw6#F_t>FX-Ffw6#-FJ
6#-Ffw6#-F[fn6#-Ffw6#F[u>F[o-Ffw6#-FJ6#-Ffw6#-F[fn6#-Ffw6#Ffan>Fbp-Ffw6#-FJ6#-F
fw6#-F[fn6#-Ffw6#Ffbn>Faq-Ffw6#-FJ6#-Ffw6#-F[fn6#-Ffw6#F`cn>F^r-Ffw6#-FJ6#-Ffw6
#-F[fn6#-Ffw6#Ffcn>F[s-Ffw6#-FJ6#-Ffw6#-F[fn6#-Ffw6#Ffdn>Ffs-Ffw6#-FJ6#-Ffw6#-F
[fn6#-Ffw6#F^en>F_t-Ffw6#-FJ6#-Ffw6#-F[fn6#-Ffw6#FQ>F[u-Ffw6#-FJ6#-Ffw6#-F[fn6#
-Ffw6#FU>Ffan-Ffw6#-FJ6#-Ffw6#-F[fn6#-FfwFau>Ffbn-Ffw6#-FJ6#-Ffw6#-F[fn6#-FfwFc
u>F`cn-Ffw6#-FJ6#-Ffw6#-F[fn6#-FfwFeu>Ffcn-Ffw6#-FJ6#-Ffw6#-F[fn6#-FfwFhu>Ffdn-
Ffw6#-FJ6#-Ffw6#-F[fn6#-FfwFju>F^en-Ffw6#-FJ6#-Ffw6#-F[fn6#-FfwF\v>8G-Fdt6$FaoF
^dm>-F_`oFa_mFH>-F_`oF_amFX>-F_`oFf`mF[o>-F_`o6$FRF^dmFbp>-F_`oFh`mFaq>-F_`oFaa
mF^r>-F_`oFj`mF[s>-F_`oFa`oFfs@$F^vC%-Fav6#Q0Initial~system:F$-Ffcl6&F_tF[uFfan
Ffbn-Ffcl6&F`cnFfcnFfdnF^en@$92-&F"6#%"RG6*FQFUFboFgoF[pFdoFioF]p@$F^vC%-Fav6'F
aw-Ffw6#-FJ6#-Ffw6#FS-Ffw6#-FJ6#-Ffw6#Fgn-Ffw6#-FJ6#-Ffw6#FV-Ffw6#-FJ6#-Ffw6#Fi
n-Fav6$Fdw-Ffw6#-FJ6#-Ffw6#-&F"6#F^xF_x-Fav6#Q;system~after~substitution:F$@%91
C*F[[nF\[nF][nF^[nF_[nF`[nFa[nFb[nC$Fd[nFf[nOF_`oF$F$F$6#Faz6en7&FdzFeoF^dlF[\n
7&FdzFeo"#i"#%)7&FdzFeoFeo"#v7&FdzFeoFeo"#V7&FdzFeoFeoF\]lFheo7&FdzFeoFeo"#w7&F
dzFeoFeo"#QFjeoF]fo7&FdzFeoFeoF\emFafoFafoFafoFafoFafoFafoFafoFg\nFg\nFg\nFg\nF
g\nFg\nFg\nFg\n7&FdzFeoFeo"#:7&FdzFeo"#="#K7&FdzFeo"#MFd]n7&FdzFeoFh\lFd\n7&Fdz
Feo"#mFfzFdfoFgfoFifoFjfoF\[l7&FdzFeoFazF\]l7&FdzFeoFedl"#o7&FdzFeoFgcmFd\lF\\l
7&FdzFeoFi\nFh\l7&FdzFeoFeoFacm7&FdzFeoFazFa[l7&FdzFeoFRFjdm7&FdzFeoFRF\]l7&Fdz
FeoFeoFidl7&FdzFeoFi\nFadl7&FdzFeoFcdlFhfo7&FdzFeoF`\nFedl7&FdzFeoFh\lFb\nFfgoF
ggoFhgoFigo7&FdzFeoF^dmF\]n7&FdzFeoFffoFfel7&FdzFeoFeo""(FdtFabow,6*F[flF\flF]f
lF^flF_flF`flFaflFbfl6)%$dabG%$dacG%$dadG%$dbcG%$dbdG%$dcdG%$RezG6"F$C*>FH-FJ6#
,&F_hmFRF]hmFeo>FX-FJ6#,&FbhmFR*&F[pFRFboFRFeo>F[o-FJ6#,&FfhmFR*&F[pFRFgoFRFeo>
Fbp-FJ6#,&FghmFR*&FdoFRFboFRFeo>Faq-FJ6#,&FihmFRF`jmFeo>F^r-FJ6#,&F[jmFR*&FioFR
FgoFRFeo>F[s-FJ6#,.*$F[oFhqFR*(FHFRF[oFRF^rFRFip*&FXFaoF^rFRFR*&FHFRFaqFaoFR*(F
HFRFbpFRF^rFRFeo*(FXFRF[oFRFaqFRFeo-Fav6$Q0Resultant:~~~%aF$F[sF$F$F$6#F]cm6+7&
FdzFeoFi\n""'7&FdzFeoFeoFcdl7&FdzFeoFa\lFacmFg[pFh[pFg[pFh[pF]fo7&FdzFeoFeoFb]n
%*zamprocl1Gw-61F*F+F,F-F.F/F0F1F2F3F4F5>F7F%>FhemF%>F[fmF%64F^fmF_fmF`fmFafmFb
fmFcfmFdfmFefmFffmF=F>F?F@FAFB%%res2GFg_nFD6"F$C4>FH-FJ6#Fcgm>FX-FJ6#Fegm>F[o-F
J6#Figm>Fbp-FJ6#F]hm>Faq-FJ6#F_hm>F^r-FJ6#Fahm>F[s-FJ6#Fehm>Ffs-FJ6#Fihm>F[uF\o
>FfanFcp>FfbnFbq>F`cnF_r>FfcnF\s>FfdnFgs>F^en-FJ6#,&*$,&*&F[uFRFfdnFRFR*&F`cnFR
FfbnFRFeoFaoFR*&,&*&F[uFRFfcnFRFR*&F`cnFRFfanFRFeoFR,&*&FfanFRFfdnFRFR*&FfcnFRF
fbnFRFeoFRFeo@$F]boC&>85F\u>F_tFfim-Fav6$F^wFd_pFdjm>F[`n-&F"6#F^^n61FHFXF[oFbp
FaqF^rF[sFfsFSFgnFVFin/._F$F8F^v/._F$F\fmF%/._F$FiemF^eoOF[`nF$F$F$6#Faz697&Fdz
FeoFedm"#z7&FdzFeoFeoFedm7&FdzFeoF_dlFh\l7&FdzFeoFdelFjdmFccm7&FdzFeoFcelF[fo7&
FdzFeoF^elFf\l7&FdzFeoFeoFa\l7&FdzFeoFc\l"#^F\[lF^[lF`[lFb[lFd[lFf[l7&FdzFeoFeo
"#pFg\n7&FdzFeoFi\n"#&*7&FdzFeoFRF[[l7&FdzFeoFd\nF\dmFj\nF\\l7&FdzFeoFfeoF]]lFd
tF$
